Worksheet3.Website/Models/ErrorViewModel.cs
using System;

namespace Worksheet3.Website.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Worksheet3.Website/Controllers/GamesController.cs
using System.Threading.Tasks;
using GameDataManagementServiceReference;
using Microsoft.AspNetCore.Mvc;
using Worksheet3.Facade;

namespace Worksheet3.Website.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGameManagementService _gameManagementService;

        public GamesController(IGameManagementService gameManagementService)
        {
            _gameManagementService = gameManagementService;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            return View(await _gameManagementService.GetGames());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameDto gameDto = await _gameManagementService.GetGame(id.Value);

            if (gameDto == null)
            {
                return NotFound();
            }

            return View(gameDto);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Active,Id,Name,Price")] GameDto gameDto)
        {
            if (ModelState.IsValid)
            {
                await _gameManagementService.CreateGame(gameDto);
                return RedirectToAction(nameof(Index));
            }

            return View(gameDto);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameDto gameDto = await _gameManagementService.GetGame(id.Value);

            if (gameDto == null)
            {
                return NotFound();
            }
            return View(gameDto);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Active,Id,Name,Price")] GameDto gameDto)
        {
            if (id != gameDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _gameManagementService.UpdateGame(gameDto);

                return RedirectToAction(nameof(Index));
            }
            return View(gameDto);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameDto gameDto = await _gameManagementService.GetGame(id.Value);

            if (gameDto == null)
            {
                return NotFound();
            }

            return View(gameDto);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _gameManagementService.DeleteBrand(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Worksheet3.Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Worksheet3.Website.Models;

namespace Worksheet3.Website.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Worksheet3.Website/Views/Games/Create.cshtml
@model GameDataManagementServiceReference.GameDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GameDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
	        <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Worksheet3.Website/Views/Games/Delete.cshtml
@model GameDataManagementServiceReference.GameDto

@{
	ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>GameDto</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Price)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Price)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

Worksheet3.Website/Views/Games/Details.cshtml
@model GameDataManagementServiceReference.GameDto

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>GameDto</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Price)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Price)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>

Worksheet3.Website/Views/Games/Edit.cshtml
@model GameDataManagementServiceReference.GameDto

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GameDto</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Price" class="control-label"></label>
				<input asp-for="Price" class="form-control" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Worksheet3.Website/Views/Games/Index.cshtml
@model IEnumerable<GameDataManagementServiceReference.GameDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
	        <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
	        <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Worksheet3.Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Worksheet3.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Worksheet3.Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Worksheet3.Website</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Worksheet3.Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>